// code/react_1/src/components/List/List.jsx
import React, { Component } from 'react';

export default class List extends Component {

    btnClick = (schoolName) => {
        this.props.getSchool(schoolName);
    };

    render () {
        let { listArr } = this.props;
        return (
            <div>
                {
                    listArr.map( item => {
                        return (
                            <div key={item.idno}>
                                <h5>{item.name}</h5>
                                <button onClick={this.btnClick.bind(this, item.name)}>选择喜欢的学校</button>
                            </div>
                        );
                    } )
                }
            </div>
        );
    };
};

// code/vue_2/src/components/List.vue
<template>
    <div class="list">
        <div v-for="item in listArr" :key="item.idno">
            <h5>{{item.name}}</h5>
        </div>
        <!-- 插槽 -->
        <slot></slot>
    </div>
</template>

<script>
export default {
    name: 'list',
    props: {
        listArr: {
            type: Array
        }
    }
}
</script>
